set -u
T=5961922b9a309055a75bc7302e5c852c5c51d59c
D="devpath-notification-svc devpath-ai-svc devpath-lcs-svc devpath-community-svc devpath-learning-svc devpath-sandbox-svc devpath-platform-svc devpath-gateway"
echo "### $(date -u +%T) argo apps"; sudo kubectl -n argocd get applications -o custom-columns=NAME:.metadata.name,SYNC:.status.sync.status,HEALTH:.status.health.status,REV:.status.sync.revision
echo "### apps at target: $(sudo kubectl -n argocd get applications -o jsonpath='{range .items[*]}{.status.sync.revision}{"\n"}{end}' | grep -c $T) / 16"
echo "### deployments (template startupProbe / paused / RS)"; sudo kubectl -n devpath get deploy $D -o custom-columns=NAME:.metadata.name,PAUSED:.spec.paused,READY:.status.readyReplicas,UPDATED:.status.updatedReplicas,GEN:.metadata.generation,OBS:.status.observedGeneration,SP_PERIOD:.spec.template.spec.containers[0].startupProbe.periodSeconds,SP_FT:.spec.template.spec.containers[0].startupProbe.failureThreshold,SP_PATH:.spec.template.spec.containers[0].startupProbe.httpGet.path
echo "### replicasets with desired>0 (expect exactly the 8 old ones)"; sudo kubectl -n devpath get rs -o custom-columns=NAME:.metadata.name,OWNER:.metadata.ownerReferences[0].name,DESIRED:.spec.replicas,CREATED:.metadata.creationTimestamp | grep -E 'notification-svc|ai-svc|lcs-svc|community-svc|learning-svc|sandbox-svc|platform-svc|gateway' | awk '$3>0'
echo "### RS created today (expect none)"; sudo kubectl -n devpath get rs -o custom-columns=NAME:.metadata.name,CREATED:.metadata.creationTimestamp | grep -c "$(date -u +%F)" || true
echo "### pods (8 services)"; sudo kubectl -n devpath get pods -o custom-columns=NAME:.metadata.name,PHASE:.status.phase,RESTARTS:.status.containerStatuses[*].restartCount,STARTED:.status.startTime | grep -E 'notification-svc|ai-svc|lcs-svc|community-svc|learning-svc|sandbox-svc|platform-svc|gateway'
echo "### fence SA"; sudo kubectl -n devpath get sa devpath-migration-fence -o jsonpath='{.imagePullSecrets}'; echo; sudo kubectl -n devpath get sa devpath-migration-fence -o jsonpath='{.metadata.annotations.kubectl\.kubernetes\.io/last-applied-configuration}' | grep -o '"imagePullSecrets":\[[^]]*\]' || echo "(imagePullSecrets NOT in last-applied)"
echo "### migration app"; sudo kubectl -n argocd get application devpath-migration -o jsonpath='{.status.sync.status} {.status.health.status} {.status.sync.revision}'; echo
